### ISSUE TITLE
Position not good

### ISSUE THREAD

**Issue by glureau** [Link2Twenty/l2t-context-menu#3]
Hello !
I've quickly tried your context menu, and it's displayed properly, but not at the right place.
I've started from the polymer starter kit here: https://developers.google.com/web/tools/polymer-starter-kit/
I tried to put a context menu in the content area but there is an offset of the left bar + the top bar :/
Maybe I did something wrong?

**Comment by Link2Twenty** [comment]
Hi, 
Can you tell me which browser you were using, give me a snippet of your code and upload a picture of what you mean.

Thanks

**Comment by Link2Twenty** [comment]
OK, I've succeeded in recreating the bug, it seems to only be a problem when the menu is open. I'll look into it.

**Comment by Link2Twenty** [comment]
**Issue (Menu open)**
![issuecontext](https://cloud.githubusercontent.com/assets/3534427/13671188/59c14948-e6c6-11e5-9e3b-68a76e5f88e5.gif)

**No Issue (Menu closed)**
![issuemenuclosed](https://cloud.githubusercontent.com/assets/3534427/13671189/59c896c6-e6c6-11e5-9797-9c75ec61b083.gif)

**Comment by Link2Twenty** [comment]
Right the way to fix this is to put l2t-context-menu out side of the paper-drawer-panel just below the toast at the bottom.


Try putting this code in after the paper toast

``` HTML
	<l2t-context-menu parentclass="mainToolbar" linkcolor="#fff">
	  <paper-menu class="list" attr-for-selected="data-route" selected="[[route]]">
		  <a data-route="home" href="{{baseUrl}}">
			<iron-icon icon="home"></iron-icon>
			<span>Home</span>
		  </a>
		  <a data-route="users" href="users">
			<iron-icon icon="info"></iron-icon>
			<span>Users</span>
		  </a>
		  <a data-route="contact" href="contact">
			<iron-icon icon="mail"></iron-icon>
			<span>Contact</span>
		  </a>
	  </paper-menu>
	</l2t-context-menu>
```

**Comment by glureau** [comment]
Good job!
Thanks for the fix, I'll try it soon ;-)
