### ISSUE TITLE
Customer CSS properties

### ISSUE THREAD

**Issue by awaumann** [Link2Twenty/l2t-context-menu#6]
You should consider using custom CSS properties for color styles in place of attributes.

**Comment by Link2Twenty** [comment]
How does that work? Can you have more than one style per app, or would they all have to look the same?

**Comment by Link2Twenty** [comment]
Thanks for the idea, I'd never used them before :+1: 

I've added them now,

**Comment by awaumann** [comment]
Sorry I didn't get back to you on that, I hadn't gotten on GitHub until now but great to know you've added it in :smile:
